name: Build Android AAB
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Install Expo CLI
        run: npm install -g @expo/cli
        
      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean
        
      - name: Show gradle files content
        run: |
          echo "=== build.gradle ==="
          cat android/build.gradle
          echo "=== app/build.gradle ==="
          cat android/app/build.gradle
        
      - name: Manually set API 35 in build.gradle
        run: |
          # Replace the entire compileSdkVersion and targetSdkVersion lines
          sed -i '/compileSdkVersion/c\    compileSdkVersion = 35' android/build.gradle
          sed -i '/targetSdkVersion/c\    targetSdkVersion = 35' android/build.gradle
          
      - name: Manually set API 35 in app/build.gradle  
        run: |
          sed -i '/compileSdk/c\    compileSdk = 35' android/app/build.gradle
          sed -i '/targetSdk/c\    targetSdk = 35' android/app/build.gradle
          
      - name: Verify changes
        run: |
          echo "=== Updated build.gradle ==="
          cat android/build.gradle | grep -A2 -B2 "compileSdk\|targetSdk"
          echo "=== Updated app/build.gradle ==="
          cat android/app/build.gradle | grep -A2 -B2 "compileSdk\|targetSdk"
        
      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/aerofit-release.keystore
            
      - name: Configure signing
        run: |
          cat >> android/app/build.gradle << 'GRADLE'
          
          android.buildTypes.release.signingConfig = android.signingConfigs.create("release") {
              storeFile file('aerofit-release.keystore')
              storePassword '${{ secrets.KEYSTORE_PASSWORD }}'
              keyAlias '${{ secrets.KEY_ALIAS }}'
              keyPassword '${{ secrets.KEYSTORE_PASSWORD }}'
          }
          GRADLE
        
      - name: Build AAB
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
