name: Build Android AAB
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Install Expo CLI
        run: npm install -g @expo/cli
        
      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean
        
      - name: Generate keystore
        run: |
          keytool -genkeypair -v -storetype PKCS12 \
            -keystore android/app/my-upload-key.keystore \
            -alias my-key-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass password \
            -keypass password \
            -dname "CN=Aerofit, OU=Unknown, O=Unknown, L=Unknown, ST=Unknown, C=US"
            
      - name: Configure signing in build.gradle
        run: |
          cat >> android/app/build.gradle << 'GRADLE'
          
          android.buildTypes.release.signingConfig = android.signingConfigs.create("release") {
              storeFile file('my-upload-key.keystore')
              storePassword 'password'
              keyAlias 'my-key-alias'
              keyPassword 'password'
          }
          GRADLE
        
      - name: Build release AAB
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease --no-daemon
          
      - uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab
