name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          
      - run: npm install
      
      - run: npx expo export --platform android
      
      - name: Build APK with Gradle
        run: |
          npx expo prebuild --platform android
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
          
      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
