name: Generate Keystore (Run Once Only)
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair -v -storetype PKCS12 \
            -keystore aerofit-release.keystore \
            -alias aerofit-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass mypassword123 \
            -keypass mypassword123 \
            -dname "CN=Aerofit, OU=Dev, O=Aerofit, L=Dallas, ST=TX, C=US"
          
      - name: Convert to base64
        run: base64 -w 0 aerofit-release.keystore > keystore-base64.txt
          
      - uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            aerofit-release.keystore
            keystore-base64.txt
